# Generated by Django 5.2.8 on 2025-11-19 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_objednavky', models.DateField(verbose_name='Datum objednávky')),
                ('stav', models.CharField(choices=[('uzivatel', 'Založená uživatelem'), ('obsluha', 'Založená obsluhou jídelny'), ('zrusena_uzivatel', 'Zrušená uživatelem'), ('zrusena_obsluha', 'Zrušená obsluhou'), ('vydana', 'Vydaná'), ('nevyzvednuta', 'Nevyzvednutá')], default='uzivatel', max_length=20, verbose_name='Stav objednávky')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jidelnicek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.jidelnicek', verbose_name='Jídelníček')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objednavky', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'unique_together': {('uzivatel', 'datum_objednavky')},
            },
        ),
    ]
