# Generated by Django 5.2.8 on 2025-11-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
        ('objednavky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objednavka',
            name='jidelnicek',
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='stav',
            field=models.CharField(choices=[('uzivatel', 'Založená uživatelem'), ('obsluha', 'Založená obsluhou'), ('zrusena_uzivatel', 'Zrušená uživatelem'), ('zrusena_obsluha', 'Zrušená obsluhou'), ('vydana', 'Vydaná'), ('nevyzvednuta', 'Nevyzvednutá')], default='obsluha', max_length=20, verbose_name='Stav objednávky'),
        ),
        migrations.CreateModel(
            name='PolozkaObjednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet', models.PositiveIntegerField(default=1, verbose_name='Počet')),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.jidlo', verbose_name='Jídlo')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='objednavky.objednavka')),
            ],
            options={
                'verbose_name': 'Položka objednávky',
                'verbose_name_plural': 'Položky objednávky',
            },
        ),
    ]
