# Generated by Django 5.2.8 on 2025-11-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0002_remove_objednavka_jidelnicek_alter_objednavka_stav_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objednavka',
            options={'ordering': ['-datum_objednavky', 'uzivatel']},
        ),
    ]
