# Generated by Django 5.2.8 on 2025-11-19 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
        ('objednavky', '0003_alter_objednavka_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objednavka',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='objednavka',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='objednavka',
            name='datum_vydeje',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objednavky', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PoložkaObjednavky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.jidlo')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='objednavky.objednavka')),
            ],
        ),
        migrations.DeleteModel(
            name='PolozkaObjednavky',
        ),
        migrations.RemoveField(
            model_name='objednavka',
            name='created',
        ),
        migrations.RemoveField(
            model_name='objednavka',
            name='datum_objednavky',
        ),
        migrations.RemoveField(
            model_name='objednavka',
            name='poznamka',
        ),
        migrations.RemoveField(
            model_name='objednavka',
            name='stav',
        ),
        migrations.RemoveField(
            model_name='objednavka',
            name='updated',
        ),
    ]
