# Generated by Django 5.2.8 on 2025-11-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
        ('objednavky', '0004_alter_objednavka_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoložkaObjednavky',
            new_name='PolozkaObjednavky',
        ),
    ]
