# Generated by Django 5.2.8 on 2025-11-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
        ('objednavky', '0005_rename_položkaobjednavky_polozkaobjednavky'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polozkaobjednavky',
            name='objednavka',
        ),
        migrations.RemoveField(
            model_name='polozkaobjednavky',
            name='jidlo',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vydeje', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'datum_vydeje')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.polozkajidelnicku')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='objednavky.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Objednavka',
        ),
        migrations.DeleteModel(
            name='PolozkaObjednavky',
        ),
    ]
