# Generated by Django 5.2.8 on 2025-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0006_remove_polozkaobjednavky_objednavka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
