# Generated by Django 5.2.8 on 2025-11-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0007_orderitem_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('zalozena-obsluhou', 'Založená obsluhou'), ('objednano', 'Objednáno'), ('zruseno-uzivatelem', 'Zrušeno uživatelem'), ('zruseno-obsluhou', 'Zrušeno obsluhou'), ('vydano', 'Vydáno'), ('nevyzvednuto', 'Nevyzvednuto')], default='zalozena-obsluhou', max_length=32),
        ),
    ]
