# Generated by Django 5.2.8 on 2025-11-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0008_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky'},
        ),
    ]
