# Generated by Django 5.2.8 on 2025-11-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
        ('objednavky', '0009_alter_order_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menu_item')},
        ),
    ]
