# Generated by Django 5.2.9 on 2026-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0010_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky uživatelů'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Objednaná jídla', 'verbose_name_plural': 'Objednaná jídla'},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('zalozena-obsluhou', 'Založená obsluhou'), ('objednano', 'Objednáno'), ('zruseno-uzivatelem', 'Zrušeno uživatelem'), ('zruseno-obsluhou', 'Zrušeno obsluhou'), ('vydano', 'Vydáno'), ('nevyzvednuto', 'Nevyzvednuto')], default='objednano', max_length=32),
        ),
    ]
