# Generated by Django 5.2.9 on 2026-01-10 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0011_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='storno_datum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Storno datum'),
        ),
        migrations.AddField(
            model_name='order',
            name='storno_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Storno provedl'),
        ),
    ]
