# Generated by Django 5.2.9 on 2026-01-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0012_order_storno_datum_order_storno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datum_vydani',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum a čas vydání'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
