# Generated by Django 5.2.9 on 2026-01-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0013_order_datum_vydani_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='datum_vydani',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vydano',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('zalozena-obsluhou', 'Založená obsluhou'), ('objednano', 'Objednáno'), ('zruseno-uzivatelem', 'Zrušeno uživatelem'), ('zruseno-obsluhou', 'Zrušeno obsluhou'), ('castecne-vydano', 'Částečně vydáno'), ('vydano', 'Vydáno'), ('nevyzvednuto', 'Nevyzvednuto')], default='objednano', max_length=32),
        ),
    ]
