# Generated by Django 5.2.9 on 2026-01-11 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0015_rfidkarta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidkarta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_karty', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
    ]
