# Generated by Django 5.2.9 on 2026-01-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0017_userrfid_delete_rfidkarta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Provedeno')),
                ('date_from', models.DateField(verbose_name='Datum od')),
                ('date_to', models.DateField(verbose_name='Datum do')),
                ('orders_affected', models.PositiveIntegerField(default=0, verbose_name='Ovlivněných objednávek')),
                ('items_affected', models.PositiveIntegerField(default=0, verbose_name='Ovlivněných položek')),
                ('total_price_diff', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Celkový cenový rozdíl')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Provedl')),
            ],
            options={
                'verbose_name': 'Log přepočtu cen',
                'verbose_name_plural': 'Logy přepočtů cen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecalculationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Stará cena')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nová cena')),
                ('price_diff', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Rozdíl')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objednavky.orderitem')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='objednavky.pricerecalculationlog')),
            ],
            options={
                'verbose_name': 'Detail přepočtu',
                'verbose_name_plural': 'Detaily přepočtu',
            },
        ),
    ]
