# Generated by Django 5.2.8 on 2025-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vklad',
            name='status',
            field=models.CharField(choices=[('standard', 'Standardní vklad'), ('nulovani_konta', 'Nulování konta')], default='standard', max_length=32),
        ),
    ]
