# Generated by Django 5.2.8 on 2025-11-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_identifikacni_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identifikacni_medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifikační médium'),
        ),
    ]
