# Generated by Django 5.2.9 on 2026-01-08 13:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objednavky', '0011_alter_order_options_alter_orderitem_options_and_more'),
        ('vydej', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VydejOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Výdej objednávky',
                'verbose_name_plural': 'Výdej objednávek',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objednavky.order',),
        ),
        migrations.CreateModel(
            name='VydejniUctenka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vydeje', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum a čas výdeje')),
                ('celkova_cena', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Celková cena')),
                ('celkova_dotace', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Celková dotace')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vydejni_uctenka', to='objednavky.order', verbose_name='Objednávka')),
                ('vydal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vydane_objednavky', to=settings.AUTH_USER_MODEL, verbose_name='Vydal')),
            ],
            options={
                'verbose_name': 'Výdejní účtenka',
                'verbose_name_plural': 'Výdejní účtenky',
                'ordering': ['-datum_vydeje'],
            },
        ),
        migrations.CreateModel(
            name='PolozkaUctenky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_jidla', models.CharField(max_length=255, verbose_name='Název jídla')),
                ('druh_jidla', models.CharField(max_length=100, verbose_name='Druh jídla')),
                ('mnozstvi', models.PositiveIntegerField(verbose_name='Množství')),
                ('cena_za_kus', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena za kus')),
                ('dotace_za_kus', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Dotace za kus')),
                ('uctenka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='vydej.vydejniuctenka', verbose_name='Účtenka')),
            ],
            options={
                'verbose_name': 'Položka účtenky',
                'verbose_name_plural': 'Položky účtenky',
            },
        ),
    ]
