# Generated by Django 5.2.9 on 2026-01-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0011_alter_order_options_alter_orderitem_options_and_more'),
        ('vydej', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrehledProKuchyni',
            fields=[
            ],
            options={
                'verbose_name': 'Přehled pro kuchyni',
                'verbose_name_plural': 'Přehled pro kuchyni',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objednavky.order',),
        ),
    ]
