# Generated by Django 5.2.9 on 2026-01-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objednavky', '0013_order_datum_vydani_order_updated_at'),
        ('vydej', '0003_prehledprokuchyni'),
    ]

    operations = [
        migrations.CreateModel(
            name='StornovaneObjednavky',
            fields=[
            ],
            options={
                'verbose_name': 'Stornovaný účet',
                'verbose_name_plural': 'Stornované účty',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('objednavky.order',),
        ),
    ]
