"""
Django settings for kliknijidlo project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('!dps&@jrvluhk!3c5l5ci@q7%uw+44ex2g@4z8#^9&jc)cmm*1')

# Validate SECRET_KEY in production
if not SECRET_KEY:
    if os.getenv('DJANGO_DEBUG', 'False') == 'False':
        raise ValueError(
            "DJANGO_SECRET_KEY must be set in production. "
            "Generate one using: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )
    else:
        # Development fallback - NEVER use in production!
        SECRET_KEY = 'django-insecure-dev-key-' + secrets.token_urlsafe(32)
        print("WARNING: Using auto-generated SECRET_KEY for development only!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Allowed hosts for production
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]  # Clean whitespace

# CSRF Trusted Origins (for HTTPS)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'https://jidelna.kliknijidlo.cz').split(',')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS if origin.strip()]

# Security settings for production
if not DEBUG:
    # SSL/HTTPS Settings
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'
    
    # Security Headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Referrer Policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # For reverse proxy (Nginx/Apache)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Development settings - allow HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Session timeout (4 hours)
SESSION_COOKIE_AGE = 14400
SESSION_SAVE_EVERY_REQUEST = False

AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = '/jidelnicek/dashboard/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/'  # RFID login page

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_extensions',

    "users",
    "jidelnicek",
    "objednavky",
    'import_export',
    'dotace',
    'canteen_settings',
    'widget_tweaks',
    'vydej_jidel',
    'frontend',
    'vydej',
    'vydej_frontend',
    'reporty',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kliknijidlo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.user_balance', 
                'canteen_settings.context_processors.footer_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'kliknijidlo.wsgi.application'

# Database
# Database configuration from environment
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'kliknijidlo_dev'),
        'USER': os.getenv('DB_USER', 'kliknijidlo_user'),
        'PASSWORD': os.getenv('dev_password_123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.getenv('DB_SSLMODE', 'prefer'),
        },
    }
}

# Validate database password in production
if not DEBUG and not DATABASES['default']['PASSWORD']:
    raise ValueError("DB_PASSWORD must be set in production!")



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'cs-cz'
TIME_ZONE = 'Europe/Prague'
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'filters': ['require_debug_false'],
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Email configuration (for error notifications and admin alerts)
if os.getenv('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', os.getenv('EMAIL_HOST_USER'))
    SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
    
    # Admin email for error notifications
    admin_email = os.getenv('ADMIN_EMAIL')
    if admin_email:
        ADMINS = [('Admin', admin_email)]
        MANAGERS = ADMINS
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Content Security (allowed file extensions for uploads if applicable)
ALLOWED_UPLOAD_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.pdf', '.doc', '.docx', '.xls', '.xlsx']

# Jazzmin Admin Configuration
JAZZMIN_SETTINGS = {
    "site_title": "KlikniJídlo Admin",
    "site_header": "KlikniJídlo",
    "site_brand": "Kliknijidlo.cz",
    "show_ui_builder": DEBUG,  # Only show in development
    
    "icons": {
        # Uživatelé & autentizace
        "auth.User": "fas fa-user-circle",
        "auth.Group": "fas fa-users-cog",
        "users.CustomUser": "fas fa-id-card-alt",
        "users.Vklad": "fas fa-cash-register",
        
        # Dotace
        "dotace.Dotace": "fas fa-hand-holding-usd",
        "dotace.DotacniPolitika": "fas fa-file-contract",
        "dotace.SkupinoveNastaveni": "fas fa-users-gear",
        
        # Jídelníčky & jídla
        "jidelnicek.Alergen": "fas fa-triangle-exclamation",
        "jidelnicek.DruhJidla": "fas fa-utensils",
        "jidelnicek.Jidelnicek": "fas fa-calendar-days",
        "jidelnicek.Jidlo": "fas fa-bowl-food",
        
        # Objednávky
        "objednavky.Order": "fas fa-shopping-basket",
        "objednavky.OrderItem": "fas fa-receipt",
        
        # Nastavení jídelny
        "canteen_settings.CanteenContact": "fas fa-building",
        "canteen_settings.GroupOrderLimit": "fas fa-user-friends",
        "canteen_settings.MealPickupTime": "fas fa-clock",
        "canteen_settings.OrderClosingTime": "fas fa-stopwatch",
        
        # Výdej jídel
        "vydej_jidel.VydajiciCas": "fas fa-clock-rotate-left",
        "vydej.Vydej": "fas fa-box-open",
        "vydej.VydejOrder": "fas fa-shopping-cart",
        "vydej.VydejniUctenka": "fas fa-receipt",
        "vydej.StornovaneObjednavky": "fas fa-trash-alt",
        "vydej.PrehledProKuchyni": "fas fa-kitchen-set",
        
        # Frontend
        "frontend.Page": "fas fa-file-lines",
        "frontend.Setting": "fas fa-sliders",
        "reporty": "fas fa-chart-mixed",
        "auth": "fas fa-shield-alt",
    },
    
    "order_with_respect_to": [
        "users",
        "jidelnicek",
        "objednavky",
        "vydej",
        "vydej_jidel",
        "dotace",
        "canteen_settings",
        "frontend",
        "reporty",
        "auth",
    ],
    
    "topmenu_links": [
        {"name": "🏠 Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "📊 Reporty", "url": "admin:reporty_reportdummy_changelist", "permissions": ["auth.view_user"]},
    ],
    
    "custom_css": "css/custom-admin.css",
}

# UI customizace
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": True,
    "brand_colour": "navbar-orange",
    "accent": "accent-success",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "spacelab",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": False
}

# =============================================================================
# SECURITY NOTES FOR PRODUCTION:
# =============================================================================
# 1. Change admin URL from /admin/ to something less predictable in urls.py
#    Example: path('secure-admin-panel/', admin.site.urls)
# 
# 2. Consider adding django-axes for login attempt throttling:
#    pip install django-axes
#    https://django-axes.readthedocs.io/
#
# 3. Regular security updates:
#    pip list --outdated
#    pip install -U Django
#
# 4. Database backups:
#    Set up automated daily backups with retention policy
#
# 5. Monitor logs regularly:
#    tail -f logs/security.log
#    tail -f logs/django.log
# =============================================================================
