# Generated by Django 5.2.8 on 2025-11-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VydajiciCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_od', models.TimeField(verbose_name='Čas od')),
                ('cas_do', models.TimeField(verbose_name='Čas do')),
                ('druh_jidla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vydajici_casy', to='jidelnicek.druhjidla')),
            ],
            options={
                'verbose_name': 'Výdejní čas',
                'verbose_name_plural': 'Výdejní časy',
                'unique_together': {('druh_jidla', 'cas_od', 'cas_do')},
            },
        ),
    ]
