# Generated by Django 5.2.8 on 2025-11-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název alergenu')),
                ('ikona', models.CharField(blank=True, max_length=100, verbose_name='bi-alarm')),
            ],
            options={
                'verbose_name': 'Alergen',
                'verbose_name_plural': 'Alergeny',
            },
        ),
        migrations.CreateModel(
            name='DruhJidla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název druhu jídla')),
                ('ikona', models.CharField(blank=True, max_length=100, verbose_name='Ikona druhu jídla')),
            ],
            options={
                'verbose_name': 'Druh jídla',
                'verbose_name_plural': 'Druhy jídel',
            },
        ),
        migrations.CreateModel(
            name='Jidlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název jídla')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena')),
                ('ikona', models.CharField(blank=True, max_length=100, verbose_name='Ikona jídla')),
                ('alergeny', models.ManyToManyField(blank=True, to='jidelnicek.alergen', verbose_name='Alergeny')),
                ('druh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.druhjidla', verbose_name='Druh jídla')),
            ],
            options={
                'verbose_name': 'Jídlo',
                'verbose_name_plural': 'Jídla',
            },
        ),
        migrations.CreateModel(
            name='Jidelnicek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platnost_od', models.DateField(verbose_name='Platnost od')),
                ('platnost_do', models.DateField(verbose_name='Platnost do')),
                ('ikona', models.CharField(blank=True, max_length=100, verbose_name='Ikona jídelníčku')),
                ('jidla', models.ManyToManyField(blank=True, to='jidelnicek.jidlo', verbose_name='Jídla v jídelníčku')),
            ],
            options={
                'verbose_name': 'Jídelníček',
                'verbose_name_plural': 'Jídelníčky',
            },
        ),
        migrations.CreateModel(
            name='PolozkaJidelnicku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jidelnicek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='jidelnicek.jidelnicek')),
                ('jidlo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.jidlo')),
            ],
            options={
                'verbose_name': 'Položka jídelníčku',
                'verbose_name_plural': 'Položky jídelníčku',
            },
        ),
    ]
