# Generated by Django 5.2.8 on 2025-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jidlo',
            name='bílkoviny',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bílkoviny (g)'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='kcal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Energetická hodnota (kcal)'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='sacharidy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sacharidy (g)'),
        ),
        migrations.AddField(
            model_name='jidlo',
            name='tuky',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tuky (g)'),
        ),
    ]
