# Generated by Django 5.2.8 on 2025-11-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jidelnicek', '0002_jidlo_bílkoviny_jidlo_kcal_jidlo_sacharidy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jidelnicek',
            name='jidla',
        ),
        migrations.AddField(
            model_name='polozkajidelnicku',
            name='druh_jidla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.druhjidla', verbose_name='Druh jídla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polozkajidelnicku',
            name='jidlo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jidelnicek.jidlo', verbose_name='Jídlo'),
        ),
    ]
