# Generated by Django 5.2.9 on 2026-01-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vydej_frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RfidKarta',
        ),
    ]
