# Generated by Django 5.2.8 on 2025-11-18 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dotace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Dotace',
                'verbose_name_plural': 'Dotace',
            },
        ),
        migrations.CreateModel(
            name='DotaceProJidelniskouSkupinu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procento', models.DecimalField(blank=True, decimal_places=2, help_text='Přepis procenta', max_digits=5, null=True)),
                ('castka', models.DecimalField(blank=True, decimal_places=2, help_text='Přepis částky', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Přepis dotace pro skupinu jídla',
                'verbose_name_plural': 'Přepisy dotací pro skupiny jídel',
            },
        ),
        migrations.CreateModel(
            name='DotacniPolitika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procento', models.DecimalField(decimal_places=2, default=0, help_text='Výchozí procentní nárok na dotaci', max_digits=5)),
                ('castka', models.DecimalField(decimal_places=2, default=0, help_text='Výchozí fixní částka dotace', max_digits=8)),
                ('mesicni_limit', models.PositiveIntegerField(default=0, help_text='Maximální počet dotací za měsíc')),
            ],
        ),
        migrations.CreateModel(
            name='SkupinoveNastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerpani_debit', models.BooleanField(default=False, help_text='Skupina může čerpat do debetu')),
                ('nutnost_dobit', models.BooleanField(default=False, help_text='Skupina musí mít peníze na účtu při čerpání')),
                ('debit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximální povolený debet (v mínusu) na kontě při povoleném čerpání debetu. Např. -1500 znamená možnost čerpat až do -1500 Kč.', max_digits=8)),
            ],
            options={
                'verbose_name': 'Nastavení konta',
                'verbose_name_plural': 'Nastavení kont',
            },
        ),
    ]
