# Generated by Django 5.2.8 on 2025-11-18 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dotace', '0001_initial'),
        ('jidelnicek', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dotace',
            name='uzivatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dotaceprojidelniskouskupinu',
            name='jidelniskova_skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jidelnicek.druhjidla'),
        ),
        migrations.AddField(
            model_name='dotacnipolitika',
            name='skupina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dotacni_politika', to='auth.group'),
        ),
        migrations.AddField(
            model_name='dotaceprojidelniskouskupinu',
            name='dotacni_politika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotace_skupiny', to='dotace.dotacnipolitika'),
        ),
        migrations.AddField(
            model_name='dotace',
            name='politika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotace.dotacnipolitika'),
        ),
        migrations.AddField(
            model_name='skupinovenastaveni',
            name='skupina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nastaveni', to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='dotaceprojidelniskouskupinu',
            unique_together={('dotacni_politika', 'jidelniskova_skupina')},
        ),
    ]
