# Generated by Django 5.2.8 on 2025-11-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotace', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotacnipolitika',
            options={'verbose_name': 'Dotační politika', 'verbose_name_plural': 'Dotační politiky'},
        ),
    ]
