# Generated by Django 5.2.8 on 2025-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotace', '0003_alter_dotacnipolitika_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skupinovenastaveni',
            name='max_pocet_jidel_per_order',
            field=models.PositiveIntegerField(default=10, help_text='0 = neomezeno', verbose_name='Max počet jídel na objednávku'),
        ),
    ]
