# Generated by Django 5.2.8 on 2025-11-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotace', '0004_skupinovenastaveni_max_pocet_jidel_per_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skupinovenastaveni',
            name='max_pocet_jidel_per_order',
        ),
    ]
