# Generated by Django 5.2.9 on 2026-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Částky z objednávek', max_length=100)),
            ],
            options={
                'verbose_name': 'Report Částky',
                'verbose_name_plural': 'Reporty Částky',
                'managed': False,
            },
        ),
    ]
