# Generated by Django 5.2.8 on 2025-11-18 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jidelnicek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPickupTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.TimeField(verbose_name='Čas výdeje jídla')),
                ('druh_jidla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jidelnicek.druhjidla', verbose_name='Druh jídla')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_days_ahead', models.PositiveIntegerField(default=1, verbose_name='Dny dopředu pro objednání')),
                ('order_deadline', models.TimeField(verbose_name='Do kdy lze objednávat')),
                ('applicable_meal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jidelnicek.druhjidla', verbose_name='Druh jídla pro nastavení')),
            ],
        ),
    ]
