# Generated by Django 5.2.8 on 2025-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Kontaktní osoba')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(verbose_name='Adresa provozovny')),
            ],
            options={
                'verbose_name': 'Kontakty jídelny',
                'verbose_name_plural': 'Kontakty jídelny',
            },
        ),
    ]
