# Generated by Django 5.2.8 on 2025-11-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0002_canteencontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteencontact',
            options={'verbose_name': 'Kontakt jídelny', 'verbose_name_plural': 'Kontakty jídelny'},
        ),
        migrations.AlterModelOptions(
            name='mealpickuptime',
            options={'verbose_name': 'Výdejní čas jídla', 'verbose_name_plural': 'Výdejní časy jídel'},
        ),
        migrations.AlterModelOptions(
            name='ordersettings',
            options={'verbose_name': 'Čas pro objednání', 'verbose_name_plural': 'Časy pro objednání'},
        ),
    ]
