# Generated by Django 5.2.8 on 2025-11-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0003_alter_canteencontact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersettings',
            name='applicable_meal_type',
        ),
        migrations.DeleteModel(
            name='MealPickupTime',
        ),
        migrations.DeleteModel(
            name='OrderSettings',
        ),
    ]
