# Generated by Django 5.2.8 on 2025-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0004_remove_ordersettings_applicable_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canteencontact',
            options={'verbose_name': 'Kontakt jídelna', 'verbose_name_plural': 'Kontakty jídelny'},
        ),
        migrations.AddField(
            model_name='canteencontact',
            name='canteen_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Název jídelny'),
        ),
    ]
