# Generated by Django 5.2.8 on 2025-11-27 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0005_alter_canteencontact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderClosingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_days', models.PositiveIntegerField(default=1, verbose_name='Počet dní dopředu')),
                ('closing_time', models.TimeField(default=datetime.time(7, 0), verbose_name='Čas uzavření objednávek')),
            ],
            options={
                'verbose_name': 'Čas uzavření objednávek',
                'verbose_name_plural': 'Časy uzavření objednávek',
            },
        ),
    ]
