# Generated by Django 5.2.8 on 2025-11-27 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('canteen_settings', '0006_orderclosingtime'),
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrderLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_orders_per_day', models.PositiveIntegerField(default=1, help_text='0 = neomezeno', verbose_name='Max. počet objednávek za den')),
                ('druh_jidla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jidelnicek.druhjidla', verbose_name='Druh jídla')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_limits', to='auth.group', verbose_name='Skupina uživatelů')),
            ],
            options={
                'verbose_name': 'Limit objednávek skupiny',
                'verbose_name_plural': 'Limity objednávek skupin',
                'unique_together': {('group', 'druh_jidla')},
            },
        ),
    ]
