# Generated by Django 5.2.8 on 2025-11-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0007_grouporderlimit'),
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPickupTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_from', models.TimeField(help_text='Čas zahájení výdeje', verbose_name='Výdej od')),
                ('pickup_to', models.TimeField(help_text='Čas ukončení výdeje', verbose_name='Výdej do')),
                ('druh_jidla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_times', to='jidelnicek.druhjidla', verbose_name='Druh jídla')),
            ],
            options={
                'verbose_name': 'Výdejní čas jídla',
                'verbose_name_plural': 'Výdejní časy jídel',
                'unique_together': {('druh_jidla',)},
            },
        ),
    ]
