# Generated by Django 5.2.8 on 2025-11-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0008_mealpickuptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealpickuptime',
            name='pickup_from',
            field=models.TimeField(help_text='Čas zahájení výdeje (každý den)', verbose_name='Výdej od'),
        ),
        migrations.AlterField(
            model_name='mealpickuptime',
            name='pickup_to',
            field=models.TimeField(help_text='Čas ukončení výdeje (každý den)', verbose_name='Výdej do'),
        ),
    ]
