# Generated by Django 5.2.8 on 2025-11-27 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('canteen_settings', '0009_alter_mealpickuptime_pickup_from_and_more'),
        ('jidelnicek', '0003_remove_jidelnicek_jidla_polozkajidelnicku_druh_jidla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouporderlimit',
            name='druh_jidla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jidelnicek.druhjidla'),
        ),
        migrations.AlterField(
            model_name='grouporderlimit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='grouporderlimit',
            name='max_orders_per_day',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
