# Generated by Django 5.2.9 on 2025-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0010_alter_grouporderlimit_druh_jidla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderclosingtime',
            name='je_aktivni',
            field=models.BooleanField(default=True),
        ),
    ]
