# Generated by Django 5.2.9 on 2026-01-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_settings', '0011_orderclosingtime_je_aktivni'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Pondělí'), (1, 'Úterý'), (2, 'Středa'), (3, 'Čtvrtek'), (4, 'Pátek'), (5, 'Sobota'), (6, 'Neděle')], unique=True, verbose_name='Den v týdnu')),
                ('is_operating', models.BooleanField(default=True, verbose_name='Jídelna v provozu')),
            ],
            options={
                'verbose_name': 'Provozní den (týdenní)',
                'verbose_name_plural': 'Provozní dny (týdenní)',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='OperatingExceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('exception_type', models.CharField(choices=[('closed', '❌ Zavřeno'), ('open', '✅ Otevřeno')], default='closed', max_length=10, verbose_name='Typ výjimky')),
                ('reason', models.CharField(blank=True, help_text="Např. 'Státní svátek', 'Prázdniny', 'Mimořádný provoz'", max_length=200, verbose_name='Důvod')),
            ],
            options={
                'verbose_name': 'Výjimka z provozu',
                'verbose_name_plural': 'Výjimky z provozu',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='orderclosingtime',
            name='advance_days',
            field=models.PositiveIntegerField(default=1, help_text='Počítají se pouze provozní dny (např. 1 = o jeden provozní den dříve)', verbose_name='Počet provozních dní dopředu'),
        ),
        migrations.AlterField(
            model_name='orderclosingtime',
            name='je_aktivni',
            field=models.BooleanField(default=True, verbose_name='Aktivní nastavení'),
        ),
    ]
